export const CREATE_FuelFilling_SUCCESS = 'CREATE_FuelFilling_SUCCESS'
export const CREATE_FuelFilling_WAITING = 'CREATE_FuelFilling_WAITING'
export const CREATE_FuelFilling_FAILED = 'CREATE_FuelFilling_FAILED'
export const CREATE_FuelFilling_ERROR = 'CREATE_FuelFilling_ERROR'
// export const CREATE_FuelFilling_SERVICEERROR = 'CREATE_FuelFilling_SERVICEERROR'
// export const RESET_CREATE_FuelFilling = 'RESET_CREATE_FuelFilling'
