export const change_taskStatusForInstructExecuting_success = 'change_taskStatusForInstructExecuting_success'
export const change_taskStatusForInstructExecuting_waiting= 'change_taskStatusForInstructExecuting_waiting'
export const change_taskStatusForInstructExecuting_failed = 'change_taskStatusForInstructExecuting_failed'
export const change_taskStatusForInstructExecuting_error = 'change_taskStatusForInstructExecuting_error'
