export const GET_TrailerInfo_SUCCESS = 'GET_TrailerInfo_SUCCESS'
export const GET_TrailerInfo_WAITING = 'GET_TrailerInfo_WAITING'
export const GET_TrailerInfo_FAILED = 'GET_TrailerInfo_FAILED'
export const GET_TrailerInfo_ERROR = 'GET_TrailerInfo_ERROR'
export const GET_TrailerInfo_Unbind = 'GET_TrailerInfo_Unbind'
