export const GET_FuelFillingRecord_SUCCESS = 'GET_FuelFillingRecord_SUCCESS'
export const GET_FuelFillingRecord_WAITING = 'GET_FuelFillingRecord_WAITING'
export const GET_FuelFillingRecord_FAILED = 'GET_FuelFillingRecord_FAILED'
export const GET_FuelFillingRecord_ERROR = 'GET_FuelFillingRecord_ERROR'
export const GET_FuelFillingRecord_SERVICEERROR = 'GET_FuelFillingRecord_SERVICEERROR'

export const GET_FuelFillingRecord_More_SUCCESS = 'GET_FuelFillingRecord_More_SUCCESS'
export const GET_FuelFillingRecord_More_WAITING = 'GET_FuelFillingRecord_More_WAITING'
export const GET_FuelFillingRecord_More_FAILED = 'GET_FuelFillingRecord_More_FAILED'
export const GET_FuelFillingRecord_More_ERROR = 'GET_FuelFillingRecord_More_ERROR'
export const GET_FuelFillingRecord_More_SERVICEERROR = 'GET_FuelFillingRecord_More_SERVICEERROR'

export const CHANGE_FuelFillingSearchField = 'CHANGE_FuelFillingSearchField'
