export const get_dpRouteTaskForOveruseDieselOil_success = 'get_dpRouteTaskForOveruseDieselOil_success'
export const get_dpRouteTaskForOveruseDieselOil_failed = 'get_dpRouteTaskForOveruseDieselOil_failed'
export const get_dpRouteTaskForOveruseDieselOil_error = 'get_dpRouteTaskForOveruseDieselOil_error'
export const get_dpRouteTaskForOveruseDieselOil_waiting = 'get_dpRouteTaskForOveruseDieselOil_waiting'