export const get_accidentResponsibilityList_success = 'get_accidentResponsibilityList_success'
export const get_accidentResponsibilityList_waiting = 'get_accidentResponsibilityList_waiting'
export const get_accidentResponsibilityList_failed = 'get_accidentResponsibilityList_failed'
export const get_accidentResponsibilityList_error = 'get_accidentResponsibilityList_error'