export const GET_RouteLoadTaskListExecuting_SUCCESS = 'GET_RouteLoadTaskListExecuting_SUCCESS'
export const GET_RouteLoadTaskListExecuting_WAITING = 'GET_RouteLoadTaskListExecuting_WAITING'
export const GET_RouteLoadTaskListExecuting_FAILED = 'GET_RouteLoadTaskListExecuting_FAILED'
export const GET_RouteLoadTaskListExecuting_ERROR = 'GET_RouteLoadTaskListExecuting_ERROR'
export const GET_RouteLoadTaskListExecuting_SERVICEERROR = 'GET_RouteLoadTaskListExecuting_SERVICEERROR'  

export const Change_CarExceptionRel_SUCCESS = 'Change_CarExceptionRel_SUCCESS'
export const Change_CarExceptionRel_WAITING = 'Change_CarExceptionRel_WAITING'
export const Change_CarExceptionRel_FAILED = 'Change_CarExceptionRel_FAILED'
export const Change_CarExceptionRel_ERROR = 'Change_CarExceptionRel_ERROR'
export const Change_CarExceptionRel_SERVICEERROR = 'Change_CarExceptionRel_SERVICEERROR'
export const RESET_Change_CarExceptionRel = 'RESET_Change_CarExceptionRel'


export const Change_ExecutingLoadTaskStatus_SUCCESS = 'Change_ExecutingLoadTaskStatus_SUCCESS'
export const Change_ExecutingLoadTaskStatus_WAITING = 'Change_ExecutingLoadTaskStatus_WAITING'
export const Change_ExecutingLoadTaskStatus_FAILED = 'Change_ExecutingLoadTaskStatus_FAILED'
export const Change_ExecutingLoadTaskStatus_ERROR = 'Change_ExecutingLoadTaskStatus_ERROR'
export const Change_ExecutingLoadTaskStatus_SERVICEERROR = 'Change_ExecutingLoadTaskStatus_SERVICEERROR'
export const RESET_Change_ExecutingLoadTaskStatus = 'RESET_Change_ExecutingLoadTaskStatus'


export const Change_CarLoadStatus_SUCCESS = 'Change_CarLoadStatus_SUCCESS'
export const Change_CarLoadStatus_WAITING = 'Change_CarLoadStatus_WAITING'
export const Change_CarLoadStatus_FAILED = 'Change_CarLoadStatus_FAILED'
export const Change_CarLoadStatus_ERROR = 'Change_CarLoadStatus_ERROR'
export const Change_CarLoadStatus_SERVICEERROR = 'Change_CarLoadStatus_SERVICEERROR'
export const RESET_Change_CarLoadStatus = 'RESET_Change_CarLoadStatus'