export const GET_DriverInfo_SUCCESS = 'GET_DriverInfo_SUCCESS'
export const GET_DriverInfo_WAITING = 'GET_DriverInfo_WAITING'
export const GET_DriverInfo_FAILED = 'GET_DriverInfo_FAILED'
export const GET_DriverInfo_ERROR = 'GET_DriverInfo_ERROR'
export const GET_DriverInfo_SERVICEERROR = 'GET_DriverInfo_SERVICEERROR' 

export const GET_DriverRecord_SUCCESS = 'GET_DriverRecord_SUCCESS'
export const GET_DriverRecord_WAITING = 'GET_DriverRecord_WAITING'
export const GET_DriverRecord_FAILED = 'GET_DriverRecord_FAILED'
export const GET_DriverRecord_ERROR = 'GET_DriverRecord_ERROR'
export const GET_DriverRecord_SERVICEERROR = 'GET_DriverRecord_SERVICEERROR'  

export const GET_DriverImage_SUCCESS = 'GET_DriverImage_SUCCESS'
export const GET_DriverImage_WAITING = 'GET_DriverImage_WAITING'
export const GET_DriverImage_FAILED = 'GET_DriverImage_FAILED'
export const GET_DriverImage_ERROR = 'GET_DriverImage_ERROR'
export const GET_DriverImage_SERVICEERROR = 'GET_DriverImage_SERVICEERROR' 