export const GET_HomeMileageInfo_SUCCESS = 'GET_HomeMileageInfo_SUCCESS'
export const GET_HomeMileageInfo_WAITING = 'GET_HomeMileageInfo_WAITING'
export const GET_HomeMileageInfo_FAILED = 'GET_HomeMileageInfo_FAILED'
export const GET_HomeMileageInfo_ERROR = 'GET_HomeMileageInfo_ERROR'
export const GET_HomeMileageInfo_Unbind = 'GET_HomeMileageInfo_Unbind'
export const GET_HomeMileageInfo_SERVICEERROR = 'GET_HomeMileageInfo_SERVICEERROR' 

export const Change_HomeTaskStatus_SUCCESS = 'Change_HomeTaskStatus_SUCCESS'
export const Change_HomeTaskStatus_WAITING = 'Change_HomeTaskStatus_WAITING'
export const Change_HomeTaskStatus_FAILED = 'Change_HomeTaskStatus_FAILED'
export const Change_HomeTaskStatus_ERROR = 'Change_HomeTaskStatus_ERROR'
export const Change_HomeTaskStatus_SERVICEERROR = 'Change_HomeTaskStatus_SERVICEERROR'
export const RESET_Change_HomeTaskStatus = 'RESET_Change_HomeTaskStatus'