export const get_AccidentType_success='get_AccidentType_success'
export const get_AccidentType_failed='get_AccidentType_failed'
export const get_AccidentType_error='get_AccidentType_error'
export const get_AccidentType_waiting='get_AccidentType_waiting'