export const GET_TruckInfo_SUCCESS = 'GET_TruckInfo_SUCCESS'
export const GET_TruckInfo_WAITING = 'GET_TruckInfo_WAITING'
export const GET_TruckInfo_FAILED = 'GET_TruckInfo_FAILED'
export const GET_TruckInfo_ERROR = 'GET_TruckInfo_ERROR'
export const GET_TruckInfo_NETERROR = 'GET_TruckInfo_NETERROR' 
export const RESET_GET_TruckInfo = 'RESET_GET_TruckInfo' 

export const GET_TruckRecord_SUCCESS = 'GET_TruckRecord_SUCCESS'
export const GET_TruckRecord_WAITING = 'GET_TruckRecord_WAITING'
export const GET_TruckRecord_FAILED = 'GET_TruckRecord_FAILED'
export const GET_TruckRecord_ERROR = 'GET_TruckRecord_ERROR'
export const GET_TruckRecord_NETERROR = 'GET_TruckRecord_NETERROR' 
export const RESET_GET_TruckRecord = 'RESET_GET_TruckRecord' 

export const GET_TruckInsurance_SUCCESS = 'GET_TruckInsurance_SUCCESS'
export const GET_TruckInsurance_WAITING = 'GET_TruckInsurance_WAITING'
export const GET_TruckInsurance_FAILED = 'GET_TruckInsurance_FAILED'
export const GET_TruckInsurance_ERROR = 'GET_TruckInsurance_ERROR'
export const GET_TruckInsurance_NETERROR = 'GET_TruckInsurance_NETERROR' 
export const RESET_GET_TruckInsurance = 'RESET_GET_TruckInsurance' 