export const GET_TruckInfo_SUCCESS = 'GET_TruckInfo_SUCCESS'
export const GET_TruckInfo_WAITING = 'GET_TruckInfo_WAITING'
export const GET_TruckInfo_FAILED = 'GET_TruckInfo_FAILED'
export const GET_TruckInfo_ERROR = 'GET_TruckInfo_ERROR'
export const GET_TruckInfo_SERVICEERROR = 'GET_TruckInfo_SERVICEERROR' 

// export const GET_TruckRecord_SUCCESS = 'GET_TruckRecord_SUCCESS'
// export const GET_TruckRecord_WAITING = 'GET_TruckRecord_WAITING'
// export const GET_TruckRecord_FAILED = 'GET_TruckRecord_FAILED'
// export const GET_TruckRecord_ERROR = 'GET_TruckRecord_ERROR'
// export const GET_TruckRecord_SERVICEERROR = 'GET_TruckRecord_SERVICEERROR'  

export const GET_TruckRepairRelList_SUCCESS = 'GET_TruckRepairRelList_SUCCESS'
export const GET_TruckRepairRelList_WAITING = 'GET_TruckRepairRelList_WAITING'
export const GET_TruckRepairRelList_FAILED = 'GET_TruckRepairRelList_FAILED'
export const GET_TruckRepairRelList_ERROR = 'GET_TruckRepairRelList_ERROR'
export const GET_TruckRepairRelList_SERVICEERROR = 'GET_TruckRepairRelList_SERVICEERROR'

export const GET_TruckImage_SUCCESS = 'GET_TruckImage_SUCCESS'
export const GET_TruckImage_WAITING = 'GET_TruckImage_WAITING'
export const GET_TruckImage_FAILED = 'GET_TruckImage_FAILED'
export const GET_TruckImage_ERROR = 'GET_TruckImage_ERROR'
export const GET_TruckImage_SERVICEERROR = 'GET_TruckImage_SERVICEERROR' 

export const GET_TruckInsurance_SUCCESS = 'GET_TruckInsurance_SUCCESS'
export const GET_TruckInsurance_WAITING = 'GET_TruckInsurance_WAITING'
export const GET_TruckInsurance_FAILED = 'GET_TruckInsurance_FAILED'
export const GET_TruckInsurance_ERROR = 'GET_TruckInsurance_ERROR'
export const GET_TruckInsurance_SERVICEERROR = 'GET_TruckInsurance_SERVICEERROR' 