export const GET_WorkMileageInfo_SUCCESS = 'GET_WorkMileageInfo_SUCCESS'
export const GET_WorkMileageInfo_WAITING = 'GET_WorkMileageInfo_WAITING'
export const GET_WorkMileageInfo_FAILED = 'GET_WorkMileageInfo_FAILED'
export const GET_WorkMileageInfo_ERROR = 'GET_WorkMileageInfo_ERROR'
export const GET_WorkMileageInfo_SERVICEERROR = 'GET_WorkMileageInfo_SERVICEERROR' 